os:
  - linux
#   - osx
notifications:
  email: false
language: python
sudo: false

install:
  - pip install tox
matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=py27
  - python: "3.6"
    env: TOX_ENV=py36
script:
  - tox -e $TOX_ENV

branches:
  only:
    #- master
    - develop

addons:
  apt:
    packages:
    - libfftw3-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install fftw; fi

