notifications:
  email: false
language: python
sudo: false

install:
  - pip install tox
matrix:
  include:
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew install python fftw
      - virtualenv env -p python
      - source env/bin/activate
    python: "2.7"
    env: TOX_ENV=py27
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew install python3 fftw
      - virtualenv env -p python3
      - source env/bin/activate
    python: "3.6"
    env: TOX_ENV=py36
  - os: linux
    python: "2.7"
    env: TOX_ENV=py27
  - os: linux
    python: "3.6"
    env: TOX_ENV=py36

script:
  - tox -e $TOX_ENV

branches:
  only:
    #- master
    - develop

addons:
  apt:
    packages:
    - libfftw3-dev